version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: rubydocker
    environment:
      DB_HOST: db
    volumes:
      - ".:/app"
  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=demo
    ports:
      - "5432:5432"
    volumes:
      - "./create_db.sql:/docker-entrypoint-initdb.d/c.sql"

  lb:
    image: jfahrer/lb:v3
    environment:
      PROXY_UPSTREAM: app:4567
    ports:
      - 80:80
